export const metadata = {
  title: 'Netwire',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <section>
        {children}
    </section>
  )
}
