import PostPreview from "@/components/ui/post-preview"

export const metadata = {
    title: 'Netwire',
    description: 'Generated by create next app',
}

export default function Page() {
    return <PostPreview group='netwire'/>
}